.PHONY: clean All

All:
	@echo "----------Building project:[ Life_of_Judd - Debug ]----------"
	@"$(MAKE)" -f  "Life_of_Judd.mk"
clean:
	@echo "----------Cleaning project:[ Life_of_Judd - Debug ]----------"
	@"$(MAKE)" -f  "Life_of_Judd.mk" clean
